-- Create Table
CREATE TABLE DIVVY_TRIPDATA_202312(
	ride_id	TEXT PRIMARY KEY,
	rideable_type TEXT,	
	started_at TIMESTAMP WITHOUT TIME ZONE,
	ended_at TIMESTAMP WITHOUT TIME ZONE,
	start_station_name TEXT,
	start_station_id TEXT,
	end_station_name TEXT,
	end_station_id TEXT,
	start_lat NUMERIC,
	start_lng NUMERIC,
	end_lat	NUMERIC,
	end_lng	NUMERIC,
	member_casual TEXT
)

-- Load data
COPY DIVVY_TRIPDATA_202301 FROM 'D:\project\divvy_tripdata\202301-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202302 FROM 'D:\project\divvy_tripdata\202302-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202303 FROM 'D:\project\divvy_tripdata\202303-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202304 FROM 'D:\project\divvy_tripdata\202304-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202305 FROM 'D:\project\divvy_tripdata\202305-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202306 FROM 'D:\project\divvy_tripdata\202306-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202307 FROM 'D:\project\divvy_tripdata\202307-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202308 FROM 'D:\project\divvy_tripdata\202308-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202309 FROM 'D:\project\divvy_tripdata\202309-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202310 FROM 'D:\project\divvy_tripdata\202310-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202311 FROM 'D:\project\divvy_tripdata\202311-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);
COPY DIVVY_TRIPDATA_202312 FROM 'D:\project\divvy_tripdata\202312-divvy-tripdata.csv' WITH (FORMAT CSV, HEADER TRUE);

SELECT * FROM DIVVY_TRIPDATA_202301
LIMIT 100

-- Combine tables
CREATE TABLE DIVVY_TRIPDATA_2023 AS
SELECT * FROM DIVVY_TRIPDATA_202301
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202302
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202303
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202304
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202305
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202306
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202307
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202308
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202309
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202310
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202311
UNION ALL
SELECT * FROM DIVVY_TRIPDATA_202312

SELECT COUNT(*) FROM DIVVY_TRIPDATA_2023
